### ISSUE TITLE
关于utils包的问题，在未安装utils包的时候出现下列的问题

### ISSUE THREAD

**Issue by nulinuli** [HKUDS/GraphGPT#15]
2023-11-09 19:57:11,775	INFO worker.py:1673 -- Started a local Ray instance.
Traceback (most recent call last):
  File "../../graphgpt/eval/run_graphgpt.py", line 242, in <module>
    run_eval(args, args.num_gpus)
  File "../../graphgpt/eval/run_graphgpt.py", line 96, in run_eval
    ans_jsons.extend(ray.get(ans_handle))
  File "/home/fry/.conda/envs/graphgpt/lib/python3.8/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/fry/.conda/envs/graphgpt/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/fry/.conda/envs/graphgpt/lib/python3.8/site-packages/ray/_private/worker.py", line 2563, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::eval_model() (pid=27577, ip=172.27.37.124)
RuntimeError: The remote function failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

ray::eval_model() (pid=27577, ip=172.27.37.124)
ModuleNotFoundError: No module named 'utils'

**Comment by nulinuli** [comment]
安装之后出现这个问题
Traceback (most recent call last):
  File "../../graphgpt/eval/run_graphgpt.py", line 8, in <module>
    from utils import disable_torch_init
ImportError: cannot import name 'disable_torch_init' from 'utils' (/home/fry/.conda/envs/graphgpt/lib/python3.8/site-packages/utils/__init__.py)
是因为版本的问题吗，我安装的utils版本是1.0.1
